package com.caidong.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_address", "id", Address.class);
		arp.addMapping("t_goodsitem", "id", Goodsitem.class);
		arp.addMapping("t_headermenu", "id", Headermenu.class);
		arp.addMapping("t_homeimg", "id", Homeimg.class);
		arp.addMapping("t_seller", "id", Seller.class);
		arp.addMapping("t_store", "id", Store.class);
		arp.addMapping("t_user", "id", User.class);
	}
}

