package com.caidong.common.model;

import com.caidong.common.model.base.BaseGoodsitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goodsitem extends BaseGoodsitem<Goodsitem> {
	public static final Goodsitem dao = new Goodsitem();
}
