package com.caidong.common.model;

import com.caidong.common.model.base.BaseHeadermenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Headermenu extends BaseHeadermenu<Headermenu> {
	public static final Headermenu dao = new Headermenu();
}
