package com.caidong.common.model;

import com.caidong.common.model.base.BaseHomeimg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Homeimg extends BaseHomeimg<Homeimg> {
	public static final Homeimg dao = new Homeimg();
}
