package com.caidong.common.model;

import com.caidong.common.model.base.BaseSeller;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Seller extends BaseSeller<Seller> {
	public static final Seller dao = new Seller();
}
