package com.caidong.common.model;

import com.caidong.common.model.base.BaseStore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Store extends BaseStore<Store> {
	public static final Store dao = new Store();
}
