package com.caidong.common.model;

import com.caidong.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User me = new User();
	
	public int userLogin(User user) {
		
		User result = user.findFirst("select user_name,password from t_user where user_name = ? and password = ?", user.getUserName(),user.getPassword());
		if (result == null) {
			return 0;
		}else {
			return 1;
		}
		
	}
}
