package com.caidong.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHeadermenu<M extends BaseHeadermenu<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setImgUrl(java.lang.String imgUrl) {
		set("imgUrl", imgUrl);
	}

	public java.lang.String getImgUrl() {
		return get("imgUrl");
	}

	public void setDescribe(java.lang.String describe) {
		set("describe", describe);
	}

	public java.lang.String getDescribe() {
		return get("describe");
	}

	public void setEnable(java.lang.Integer enable) {
		set("enable", enable);
	}

	public java.lang.Integer getEnable() {
		return get("enable");
	}

	public void setVersion(java.lang.Float version) {
		set("version", version);
	}

	public java.lang.Float getVersion() {
		return get("version");
	}

}
