package com.caidong.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStore<M extends BaseStore<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setStoreName(java.lang.String storeName) {
		set("store_name", storeName);
	}

	public java.lang.String getStoreName() {
		return get("store_name");
	}

	public void setStoreCode(java.lang.String storeCode) {
		set("store_code", storeCode);
	}

	public java.lang.String getStoreCode() {
		return get("store_code");
	}

	public void setStoreGrade(java.lang.Integer storeGrade) {
		set("store_grade", storeGrade);
	}

	public java.lang.Integer getStoreGrade() {
		return get("store_grade");
	}

	public void setStoreIco(java.lang.String storeIco) {
		set("store_ico", storeIco);
	}

	public java.lang.String getStoreIco() {
		return get("store_ico");
	}

	public void setStoreDescpription(java.lang.String storeDescpription) {
		set("store_descpription", storeDescpription);
	}

	public java.lang.String getStoreDescpription() {
		return get("store_descpription");
	}

	public void setStoreFansNum(java.lang.Integer storeFansNum) {
		set("store_fans_num", storeFansNum);
	}

	public java.lang.Integer getStoreFansNum() {
		return get("store_fans_num");
	}

	public void setStoreItemNum(java.lang.Integer storeItemNum) {
		set("store_item_num", storeItemNum);
	}

	public java.lang.Integer getStoreItemNum() {
		return get("store_item_num");
	}

	public void setSellerId(java.lang.Integer sellerId) {
		set("seller_id", sellerId);
	}

	public java.lang.Integer getSellerId() {
		return get("seller_id");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
	}

	public java.lang.String getUpdateTime() {
		return get("update_time");
	}

	public void setLastLoginTime(java.lang.String lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}

	public java.lang.String getLastLoginTime() {
		return get("last_login_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
