package com.caidong.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAddress<M extends BaseAddress<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSortLetter(java.lang.String sortLetter) {
		set("sort_letter", sortLetter);
	}

	public java.lang.String getSortLetter() {
		return get("sort_letter");
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		set("phone_number", phoneNumber);
	}

	public java.lang.String getPhoneNumber() {
		return get("phone_number");
	}

	public void setZipCode(java.lang.String zipCode) {
		set("zip_code", zipCode);
	}

	public java.lang.String getZipCode() {
		return get("zip_code");
	}

	public void setZoneName(java.lang.String zoneName) {
		set("zone_name", zoneName);
	}

	public java.lang.String getZoneName() {
		return get("zone_name");
	}

	public void setStreetName(java.lang.String streetName) {
		set("street_name", streetName);
	}

	public java.lang.String getStreetName() {
		return get("street_name");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

}
